name: NodeJS Docker Demo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: sajigeorgejoe/my_node_app
  IMAGE_TAG: github
  
jobs:
  build_image:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.0.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $IMAGE_NAME:$IMAGE_TAG
